[package]
name = "hyper-of"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.39"
dotenv = "0.15.0"
ethers = "2.0.14"
hyperliquid_rust_sdk = "0.5.0"
log = "0.4.22"
tokio = { version = "1.38.1", features = ["full"] }
